stages:
  - prebuild
  - test

build-message-bus:
  stage: prebuild
  image: rust:1.79-bookworm
  cache:
    - key:
        files:
          - ./core/message-bus/Cargo.lock
          - ./core/message-bus/target/CACHEDIR.TAG
      paths:
        - core/message-bus/target/debug/build
        - core/message-bus/target/debug/deps
        - core/message-bus/target/debug/prog-bot-message-bus
        - core/message-bus/target/debug/prog-bot-message-bus.d
  script:
    - cd ./core/message-bus/
    - cargo build
  only:
    - main

message-bus-test:
  stage: test
  image: rust:1.79-bookworm
  cache:
    - key:
        files:
          - ./core/message-bus/Cargo.lock
          - ./core/message-bus/target/CACHEDIR.TAG
      paths:
        - core/message-bus/target/debug/build
        - core/message-bus/target/debug/deps
        - core/message-bus/target/debug/prog-bot-message-bus
        - core/message-bus/target/debug/prog-bot-message-bus.d
  script:
    - cd ./core/message-bus/
    - tmux new -ds "messagebus-test" "cargo run"
    - sleep 2
    - cargo test
    - tmux kill-session -t "messagebus-test"
  only:
    - main

lsp-test:
  stage: test
  image: rust:1.79-bookworm
  cache:
    - key:
        files:
          - ./core/message-bus/Cargo.lock
          - ./core/message-bus/target/CACHEDIR.TAG
      paths:
        - core/message-bus/target/debug/build
        - core/message-bus/target/debug/deps
        - core/message-bus/target/debug/prog-bot-message-bus
        - core/message-bus/target/debug/prog-bot-message-bus.d
  script:
    - cd ./core/message-bus/
    - tmux new -ds "messagebus-test" "cargo run"
    - sleep 2
    - cd ../lsp
    # - cargo test
    - tmux kill-session -t "messagebus-test"
  only:
    - main

todo-test:
  stage: test
  image: rust:1.79-bookworm
  cache:
    - key:
        files:
          - ./core/message-bus/Cargo.lock
          - ./core/message-bus/target/CACHEDIR.TAG
      paths:
        - core/message-bus/target/debug/build
        - core/message-bus/target/debug/deps
        - core/message-bus/target/debug/prog-bot-message-bus
        - core/message-bus/target/debug/prog-bot-message-bus.d
  script:
    - cd ./core/message-bus/
    - tmux new -ds "messagebus-test" "cargo run"
    - sleep 2
    - cd ../todo-collector/
    # - cargo test
    - tmux kill-session -t "messagebus-test"
  only:
    - main
