stages:
  - prebuild
  - test

build-message-bus:
  stage: prebuild
  image: rust:1.79-bookworm
  cache:
    - key:
        files:
          - core/message-bus/Cargo.lock
          - core/message-bus/target/CACHEDIR.TAG
      paths:
        - core/message-bus/target/debug/build
        - core/message-bus/target/debug/deps
        - core/message-bus/target/debug/prog-bot-message-bus
        - core/message-bus/target/debug/prog-bot-message-bus.d
  script:
    - cd ./core/message-bus/
    - cargo build
  only:
    - main
    - dev

message-bus:
  stage: test
  image: rust:1.79-bookworm
  before_script:
    - apt-get update -y && apt-get install -y tmux
  script:
    - cd ./core/message-bus/
    - cargo build
    - tmux new -ds "messagebus-test" "cargo run"
    - sleep 5
    - cargo test
    - tmux kill-session -t "messagebus-test"
  only:
    - main
    - dev

linter:
  stage: test
  image: rust:1.79-bookworm
  before_script:
    - apt-get update -y && apt-get install -y tmux
  cache:
    - key:
        files:
          - core/linter/Cargo.lock
          - core/linter/target/CACHEDIR.TAG
      paths:
        - core/linter/target/debug/build
        - core/linter/target/debug/deps
  script:
    - cd ./core/message-bus/
    - cargo build
    - tmux new -ds "messagebus-test" "cargo run"
    - sleep 10
    - cd ../linter
    - cargo test
    - tmux kill-session -t "messagebus-test"
  only:
    - main

todo-collector:
  stage: test
  image: rust:1.79-bookworm
  before_script:
    - apt-get update -y && apt-get install -y tmux
  cache:
    - key:
        files:
          - core/todo-collector/Cargo.lock
          - core/todo-collector/target/CACHEDIR.TAG
      paths:
        - core/todo-collector/target/debug/build
        - core/todo-collector/target/debug/deps
  script:
    - cd ./core/message-bus/
    - cargo build
    - tmux new -ds "messagebus-test" "cargo run"
    - sleep 5
    - cd ../todo-collector/
    - cargo test
    - tmux kill-session -t "messagebus-test"
  only:
    - main
