default:
  just --list

test:
  tmux new -ds "messagebus-test"
  tmux send-keys -t messagebus-test "cargo run" Enter
  sleep 2
  cargo test
  tmux kill-session -t "messagebus-test"

entr:
  /usr/bin/ls src/**/*.rs Cargo.toml | entr cargo check

test-file-open-server:
  echo '{"type":"Subscribe","data":["FileOpened"],"context":{"sender":null,"response_to":null}}' | rlwrap websocat ws://127.0.0.1:8080/message-bus

test-file-open-client:
  http POST http://localhost:8080/open-file <<< "/home/Code/rust"

test-utterance-server:
  echo '{"type":"Subscribe","data":["UserSpeakStart","UserSpeakStop"],"context":{"sender":null,"response_to":null}}' | rlwrap websocat ws://127.0.0.1:8080/message-bus

test-utterance-client:
  http POST http://127.0.0.1:8080/utterance/start
  sleep 0.5
  http POST http://127.0.0.1:8080/utterance/stop

