test:
  tmux new -ds "messagebus-test"
  tmux send-keys -t messagebus-test "cargo run" Enter
  sleep 2
  cargo test
  tmux kill-session -t "messagebus-test"

entr:
  /usr/bin/ls src/**/*.rs Cargo.toml | entr cargo check

test-file-open:
  echo '{"type":"Subscribe","data":["FileOpened"],"context":{"sender":null,"response_to":null}}' | rlwrap websocat ws://127.0.0.1:8080/message-bus
