[package]
name = "prog-bot-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
tracing = { version = "0.1.40", features = ["async-await", "log", "log-always"] }
